version: '3'

services:
  redis:
    container_name: redis
    image: 'redis:alpine'
    restart: unless-stopped

  nodejs:
    container_name: nodejs
    build: ./nodejs
    ports:
      - '8080:8080'
    restart: on-failure
    depends_on:
      - redis
    
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - '80:80'
    restart: on-failure
    depends_on:
      - redis
      - nodejs

# networks:
#   salestagram-networks:
#     driver: bridge
