version: '3.9'

services:
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - '6379:6379'
    networks:
      - salestagram-networks
    restart: unless-stopped
  nodejs-express:
    container_name: nodejs-express
    build: ./nodejs
    ports:
      - '8080:8080'
    networks:
      - salestagram-networks
    depends_on:
      - redis
    restart: on-failure
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - '80:80'
    networks:
      - salestagram-networks
    depends_on:
      # - redis
      - nodejs-express
    restart: on-failure

networks:
  salestagram-networks:
    driver: bridge
